// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"time"

	entity "github.com/AnikinSimon/avito-test-backend/internal/models/entity"
	"github.com/google/uuid"
)

type Product struct {
	ID          uuid.UUID
	DateTime    time.Time
	Type        entity.ProductType
	ReceptionID uuid.UUID
}

type Pvz struct {
	ID               uuid.UUID
	RegistrationDate time.Time
	City             entity.City
}

type Reception struct {
	ID       uuid.UUID
	DateTime time.Time
	PvzID    uuid.UUID
	Status   entity.Status
}

type User struct {
	ID       uuid.UUID
	Email    string
	Password string
	Role     entity.Role
}
